### PR TITLE
Ba 64 retrieve inventory elements from database

### PR DESCRIPTION
**Pull request by lyio**
Retrieve inventory items from firebase via a <firebase-collection> element

### CODE REVIEW

**Comment by lyio** [comment]
@flashback2k14

**Comment by flashback2k14** [comment]
i.O., but implementation for #ba-56 not needed with firebase elements.

**Comment by lyio** [comment]
Yes, indeed. Wasn't sure what the status on that was, so I left it in for compatibility. I'll remove it.

**Comment by flashback2k14** [comment]
i.O.

**Comment by lyio** [comment]
Did you try it out?

Sebastian Kloppe notifications@github.com schrieb am Fr., 18. Sep. 2015
15:37:

**Comment by flashback2k14** [comment]
socobo-inventory-create is broken

``` html
<paper-dropdown-menu label="Kategorie" id="categoryDropdown">
   <paper-menu class="dropdown-content" selected="0">
          <template is="dom-repeat" items="[[categories]]" as="category">
            <paper-item>[[category]]</paper-item>
          </template>
        </paper-tabs> <!-- here -->
      </paper-dropdown-menu>
```

**Comment by flashback2k14** [comment]
broken 

``` html
<paper-fab id="inventory-button-add" class="button-add" icon="add" on-click="createItem"></paper-fab>
```

**Comment by flashback2k14** [comment]
please clear all inputs after successful saving. if i want to add e new item. the old is still there.

saving and showing items in listview works great.

**Comment by lyio** [comment]
Can you open a bug for whatever you mean with 'broken' and for clearing the input fields?

**Comment by flashback2k14** [comment]
finished

**Comment by flashback2k14** [comment]
i.O.

**Pull request merged**
