### PR TITLE
ba-68 Include input field in measurement and category dropdown

### PR DESCRIPTION
**Pull request by lyio**
[work in progress]
Add an input field to the measurement dropdown with an add button and list filtering

(latest bower update broke some css, not gonna fix this here, though).

Will try to pull the dropdown out into its own element and add that to the categories as well.

@flashback2k14 @hetec

### CODE REVIEW

**Comment by flashback2k14** [comment]
- works, but little unstabil.
- the layout is a mess. Please add me to the contributor and I look into it!

**Comment by lyio** [comment]
@flashback2k14 yes, I know about the layout. I eventually gave up with the button.

Could you elaborate on the unstable part?

Also, I am currently refactoring it into its own element, I will add you when I pushed that.

**Comment by flashback2k14** [comment]
if i add a new item then it's not enabled.

**Comment by flashback2k14** [comment]
branch is conflicted

**Comment by lyio** [comment]
yes, disregard this PR

**Pull request closed without merging**
